### ISSUE TITLE
[ Previous Game ] Random crashes.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#94] opened 2017-11-19 08:47 UTC
Maybe a duplicate, please close if so.

On some devices, sometimes when loading previous games the game crashes. (This was noticed for  android version 4.4.2 and 6.0.1 but not for 4.2.2 )

**Comment by panagiotissp** [comment] 2017-11-19 12:40
@ignacioch  Exact duplicate of #85 
Closing current issue

**Closed by panagiotissp** 2017-11-19 12:40 UTC
Labels: client feedback
