### ISSUE TITLE
[client feedback ] Sounds on/off does not work.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#78] opened 2017-11-16 22:21 UTC
When we deactivate the “sounds «they’re still there (sudden death, chronometer etc)

**Comment by panagiotissp** [comment] 2017-11-18 22:50
@ignacioch I made a commit b020a2e which closed issue #77 and actually fixed a bug in the code that basically when switching the stats button, the value of sounds variable changed. 
So, e.g. if user 
- set sound to off -> sound variable switches, i.e. goes to off
- and then set stats to off ->sound variable switches, i.e. goes to on...
..so they played the game with sounds on when the UI sound button was showing off

After fixing this bug I cannot reproduce anymore, so I think that was the case.
Closing current issue

**Comment by ignacioch** [comment] 2017-11-26 19:25
client said it's not working on their demo - but it works on mine. they said that 

> This is not fixed, now it does not work at all, by clicking no sound, we still have sounds

I asked for a video. Reopening until they mark it fixed.

**Comment by ignacioch** [comment] 2017-11-26 21:46
> In some cases this works, and when we go to sudden death then there is the sudden death sounds. but in some cases, like on my samsung galaxy mini it does not work. I will attach a video

Can we check on sudden death what happens with the sounds?

**Closed** 2017-11-26 22:51 UTC
Labels: client feedback
