### ISSUE TITLE
 Starting a new game

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#82] opened 2017-11-16 22:38 UTC
- Otan den exeis palies partides i tis exeis svisei na mpainei kaeutheian stin selida me tis omades

--> meaning that it shouldn't give you the popup but skip that.

**Comment by panagiotissp** [comment] 2017-11-17 21:53
It does @ignacioch .
It searches in local games and if there are no games there is no popup.

What customer probably did was to uninstall the app and install it again?
If that is so, then I remember there are cases where this happens (e.g. due to backup reasons: https://stackoverflow.com/questions/35029377/sharedpreferences-not-being-removed-on-user-uninstalling-application )

Could you also please ask the *specific device* they are testing onto? Model, Android version etc

It will be useful info when I'm trying to reproduce what customer mentioned for speculative cases

Not sure if I should close current issue or leave it on 'Waiting' on your side... please advise

**Comment by ignacioch** [comment] 2017-11-18 18:14
ok asking

**Comment by panagiotissp** [comment] 2017-11-18 23:20
@ignacioch sorry for the comment above, this should be related to the bug (that I confirmed) for issue #85 
They should be related so the fix of #85 will fix current issue too.

So, current issue remains and should be handled by me

**Comment by panagiotissp** [comment] 2017-11-20 14:44
Closed by commit 14f7c6c

**Closed by panagiotissp** 2017-11-20 14:44 UTC
Labels: client feedback
