### ISSUE TITLE
[ Congratulations ] Colouring

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#107] opened 2017-11-19 09:03 UTC
> “Felicitations” should be in the color of the winning team and the name of the team should NOT follow, like on iOS. (same for foot mode congratulation page)

**Comment by panagiotissp** [comment] 2017-11-19 12:18
This is full duplicate of issue #80 .
Closing this issue

**Closed by panagiotissp** 2017-11-19 12:18 UTC
Labels: Jokers client feedback
