### ISSUE TITLE
Jokers buying on joker page.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#122] opened 2017-11-28 22:58 UTC
> If we unlock jokers via facebook, after we are not able to buy the remaining locked ones from the joker page. We have to buy them from the store.

They mean that the lock icon they have to be clickable and show the do you want to buy popup ( the one for all jokers in French ) and purchase from there.

Again not sure what was in the original spec but let's implement it, we already have this code and it's just boiler plate.

**Comment by panagiotissp** [comment] 2017-11-29 18:13
@ignacioch can you reproduce?
It would help me a lot since I have lost the number of different apks already created. You may anyway have an updated version compared to the customer that somewhere on another issue this is resolved.

Please spend 1' to repdoruce this

**Comment by ignacioch** [comment] 2017-11-29 19:50
there is a typo on store - please change it on the app.

` attack_jokes_0` is the correct one that is deployed.

**Comment by panagiotissp** [comment] 2017-11-29 20:54
this is already handled on issue #113 
If so it is exact duplicate.

I'm closing this. however double check again to be 1000% sure
@ignacioch

**Closed by panagiotissp** 2017-11-29 20:54 UTC
