### ISSUE TITLE
Football category issue

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#124] opened 2017-11-28 23:07 UTC
I dont think its a duplicate - if it is please close it.

> In the non joker demo, the football category was unlocked and selected like all categories ( we had not bought the football mode yet ) The football category is locked and should be, unlocked only when you buy the football mode

**Comment by panagiotissp** [comment] 2017-11-29 17:12
@ignacioch should be exact duplicate of #116
I'm closing it but anyway make a double check you too

**Closed by panagiotissp** 2017-11-29 17:12 UTC
