### ISSUE TITLE
[Algorithm ]

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#86] opened 2017-11-16 22:43 UTC
-  Selection of categories doesn’t work: ex: We deselect sports but we get sports questions.

I will double check it , but that's the feedback they gave.

**Comment by panagiotissp** [comment] 2017-11-20 16:04
@ignacioch this should not be the case. I checked the mapped categories - i.e. the ids of themes in the db - for which the questions are fetched and everything seems correct.
I checked the output of my tests and only the questions from the selected categories are fetched.

E.g. the following is the output when football is not in the selected categories:

```
11-20 17:52:53.819 7874-7874/fr.devineuf V/Right now: Mapped Category Id is 1 with number of results = 107
11-20 17:52:53.823 7874-7874/fr.devineuf V/Right now: Mapped Category Id is 2 with number of results = 114
11-20 17:52:53.828 7874-7874/fr.devineuf V/Right now: Mapped Category Id is 8 with number of results = 97
11-20 17:52:53.832 7874-7874/fr.devineuf V/Right now: Mapped Category Id is 4 with number of results = 109
11-20 17:52:53.836 7874-7874/fr.devineuf V/Right now: Mapped Category Id is 5 with number of results = 110
11-20 17:52:53.840 7874-7874/fr.devineuf V/Right now: Mapped Category Id is 9 with number of results = 98
11-20 17:52:53.843 7874-7874/fr.devineuf V/Right now: Mapped Category Id is 7 with number of results = 98
11-20 17:52:53.847 7874-7874/fr.devineuf V/Right now: Mapped Category Id is 11 with number of results = 275
```

Football category theme id is 12, so the above is correct.
I have also checked the questions fetched each time.
Everything seems fine.

The only thing I can think of is that maybe the customer had football category selected, sports category deselected, that's why some ""sports"" questions came in?

Sorry, cannot reproduce.
I want more details, specific categories selections, specific question that is e.g. a sport question that should not have appeared but it did, screenshots of the flow etc

I'm closing for now.
@ignacioch  if we have extra feedback you may reopen current issue

**Closed by panagiotissp** 2017-11-20 16:04 UTC
Labels: client feedback
